# Generated by Django 3.0.8 on 2020-07-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalFinancialInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('legalAddress', models.TextField()),
                ('responsiblePersonFullname', models.CharField(max_length=60)),
                ('responsiblePersonPosition', models.CharField(max_length=50)),
                ('responsiblePersonPhoneNumber', models.CharField(max_length=50)),
                ('responsiblePersonEmail', models.CharField(max_length=50)),
                ('additionalContactPersonFullname', models.CharField(max_length=60)),
                ('additionalContactPersonPosition', models.CharField(max_length=50)),
                ('additionalContactPersonPhoneNumber', models.CharField(max_length=50)),
                ('additionalContactPersonEmail', models.CharField(max_length=50)),
            ],
        ),
    ]
